name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Virtualization tool to run/test for different architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://depot.dev/blog/docker-layer-caching-in-github-actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build using cache
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: localhost:5000/${{ github.actor }}/${{ github.event.repository.name }}:test

      - name: Run the image
        run: |
          docker images
          docker run --rm localhost:5000/${{ github.actor }}/${{ github.event.repository.name }}:test
