name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST_TAG: ankur-gupta/my-pytorch:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Virtualization tool to run/test for different architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://depot.dev/blog/docker-layer-caching-in-github-actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build using cache
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true  # Needed for testing
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.TEST_TAG }}

      - name: Run the image
        run: |
          docker images
          docker run --rm ${{ env.TEST_TAG }} pwd
