name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Virtualization tool to run/test for different architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://depot.dev/blog/docker-layer-caching-in-github-actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build using cache
        id: build-using-cache
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          # load: true  # Needed for testing
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ github.event.repository.name }}:test
          outputs: imageid

      - name: Run the image
        run: |
          echo ${{ steps.build-using-cache.outputs.imageid }}
          docker images
          docker run --rm ${{ github.event.repository.name }}:test pwd
