name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Virtualization tool to run/test for different architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://depot.dev/blog/docker-layer-caching-in-github-actions
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Build using cache
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: false
          # load: true  # Needed for testing
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ github.actor }}/${{ github.event.repository.name }}:test

      - name: Run the image
        run: |
          docker images
          docker run --rm ${{ github.actor }}/${{ github.event.repository.name }}:test pwd
